services:
  app:
    command: 
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./internal:/app/internal
      - ./cmd:/app/cmd
      - ./protobuf:/app/protobuf
      - ./pkg:/app/pkg
      - ./migrations:/app/migrations
      - ./lib:/app/lib
    env_file:
        - .env

  db:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d default_db -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      PG_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
    ports:
      - 5431:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: